---
title: "OC17 MAG Taxonomic Abundance - refined"
output: html_document
date: "2024-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(tidyr)
library(dplyr)
library(readr)
library(purrr)

library(ggplot2)
library(ggthemes)
library(patchwork)
library(RColorBrewer)
library(png)
library(pals)
```

```{r}
rootdir = "/scratch/users/rsalcedo/OC17wc_deepauto/genome_based/"
```

```{r message=FALSE, warning=FALSE}
coverm = read_csv(paste(rootdir, "refined_analysis/refined_tables/refined_coverM_all.csv", sep = ""))
genome_info = read_csv(paste(rootdir, "refined_analysis/refined_tables/refined_auto_MAGs_edited.csv", sep = ""))
```

```{r}
coverm_QC = filter(coverm, covered_fraction >= 0.50)
sample_cov = coverm_QC %>% 
  group_by(Sample) %>% 
  summarise(Mean = sum(Mean))

coverm_QC = left_join(coverm_QC, sample_cov, "Sample")
coverm_QC <- coverm_QC %>% 
  rename_with(~ "sample_cov", starts_with("Mean.y"))
coverm_QC <- coverm_QC %>% 
  rename_with(~ "genome_cov", starts_with("Mean.x"))
coverm_QC$relative = coverm_QC$genome_cov/coverm_QC$sample_cov
coverm_QC$depth = coverm_QC$Sample
coverm_QC$site = coverm_QC$Sample

coverm_QC  = coverm_QC %>%
  mutate(depth = case_when(
    endsWith(Sample, "m50m") ~ "50m",
    endsWith(Sample, "m150m") ~ "150m",
    endsWith(Sample, "m500m") ~ "500m",
    endsWith(Sample, "m1000m") ~ "1000m",
    endsWith(Sample, "m2000m") ~ "2000m",
    endsWith(Sample, "m3000m") ~ "3000m",
    endsWith(Sample, "m4000m") ~ "4000m")
  )
    
#coverm_QC$depth = as.numeric(coverm_QC$depth)

coverm_QC  = coverm_QC  %>%
  mutate(site = case_when(
    startsWith(Sample, "500m") ~ "OC2",
    startsWith(Sample, "3000m") ~ "OC3",
    startsWith(Sample, "3500m") ~ "OC4",
    startsWith(Sample, "4000m") ~ "OC5",
    startsWith(Sample, "4500m") ~ "OC6")
  )

total_data_coverage = sum(unique(coverm_QC$sample_cov))
coverm_QC$relative_total = coverm_QC$genome_cov/total_data_coverage
```

```{r}
genome_info$kingdom = sub("\\;p.*", "", genome_info$classification)
genome_info$phylum = sub(".*p__", "", genome_info$phylum)
genome_info$class = sub(".*c__", "", genome_info$class)
genome_info$kingdom = sub(".*d__", "", genome_info$kingdom)
genome_info = genome_info %>% mutate(kingdom = ifelse(kingdom == "Bacteria", "B", kingdom))
genome_info = genome_info %>% mutate(kingdom = ifelse(kingdom == "Archaea", "A", kingdom))
genome_info = genome_info %>% mutate(phylum = ifelse(class == "Gammaproteobacteria", "Gammaproteobacteria", phylum))
genome_info = genome_info %>% mutate(phylum = ifelse(class == "Alphaproteobacteria", "Alphaproteobacteria", phylum))
```

```{r}
genome_coverage = merge(genome_info, coverm_QC, by = "genome")

genome_coverage = genome_coverage %>%
  group_by(Sample) %>%
  mutate(phyla_count = n_distinct(phylum))

df2 = select(genome_coverage, c("Sample", "phyla_count"))
df2 = df2[!duplicated(df2), ]
df2$depth = df2$Sample
df2$site = df2$Sample

df2  = df2 %>%
  mutate(depth = case_when(
    endsWith(Sample, "m50m") ~ "50",
    endsWith(Sample, "m150m") ~ "150",
    endsWith(Sample, "m500m") ~ "500",
    endsWith(Sample, "m1000m") ~ "1000",
    endsWith(Sample, "m2000m") ~ "2000",
    endsWith(Sample, "m3000m") ~ "3000",
    endsWith(Sample, "m4000m") ~ "4000")
  )
    
df2  = df2  %>%
  mutate(site = case_when(
    startsWith(Sample, "500m") ~ "500",
    startsWith(Sample, "3000m") ~ "3000",
    startsWith(Sample, "3500m") ~ "3500",
    startsWith(Sample, "4000m") ~ "4000",
    startsWith(Sample, "4500m") ~ "4500")
  )

df2$Sample = NULL
df2$depth = as.numeric(df2$depth)

average_phyla_by_depth <- df2 %>%
  group_by(depth) %>%
  summarise(mean_phyla_count = mean(phyla_count))

# Print the result
print(average_phyla_by_depth)

```

```{r}
genome_coverage = merge(genome_info, coverm_QC, by = "genome")

genome_coverage = genome_coverage %>%
  group_by(Sample) %>%
  mutate(MAG_count = n_distinct(genome))

df = select(genome_coverage, c("Sample", "MAG_count"))
df = df[!duplicated(df), ]
df$depth = df$Sample
df$site = df$Sample

df  = df %>%
  mutate(depth = case_when(
    endsWith(Sample, "m50m") ~ "50",
    endsWith(Sample, "m150m") ~ "150",
    endsWith(Sample, "m500m") ~ "500",
    endsWith(Sample, "m1000m") ~ "1000",
    endsWith(Sample, "m2000m") ~ "2000",
    endsWith(Sample, "m3000m") ~ "3000",
    endsWith(Sample, "m4000m") ~ "4000")
  )
    
df  = df  %>%
  mutate(site = case_when(
    startsWith(Sample, "500m") ~ "500",
    startsWith(Sample, "3000m") ~ "3000",
    startsWith(Sample, "3500m") ~ "3500",
    startsWith(Sample, "4000m") ~ "4000",
    startsWith(Sample, "4500m") ~ "4500")
  )

df$Sample = NULL
df$depth = as.numeric(df$depth)
```

```{r}
a = aggregate(genome_coverage$relative, by=list(Category=genome_coverage$phylum, genome_coverage$Sample), FUN=sum)
unique(genome_coverage$phylum)
```


```{r}
category_colors <- c(
  "Gammaproteobacteria" = "#B3CDE3",  # Light Blue
  "Alphaproteobacteria" = "#1F78B4",  # Muted Cyan
  "Thermoplasmatota" = "#3E8E41",     # Muted Blue
  "Myxococcota_A" = "#6A3D9A",        # Deep Purple
  "Planctomycetota" = "#CAB2D9",      # Soft Purple
  "Actinobacteriota" = "#9467BD",     # Lavender
  "Thermoproteota" = "#B2DF8A",       # Muted Green
  "Hydrogenedentota" = "#0066CC",     # Forest Green
  "Desulfobacterota_B" = "#F2F2F2",   # Light Green
  "SAR324" = "#F1E3A1",               # Soft Pink
  "Chloroflexota" = "#FED9A6",        # Pale Magenta
  "Marinisomatota" = "#FB9A99",       # Coral
  "JAAXHH01" = "#E31A1C",             # Brick Red (contrast)
  "Cyanobacteria" = "#FDDAEC",        # Peach
  "Gemmatimonadota" = "#FDBF6F",      # Soft Orange
  "Myxococcota" = "#FF7F00",          # Orange (muted)
  "Halobacteriota" = "#CCEBC5",       # Light Gray (neutral)
  "UBA8248" = "#E377C2"               # Beige (neutral)
)

plot = ggplot(genome_coverage, aes(fill=phylum, color = phylum, y=relative, x=depth)) + 
  geom_bar(position="fill", stat="identity") +
  facet_grid(~factor(site, levels = c("OC6", "OC5", "OC4", "OC3", "OC2")))+
  coord_flip() +
  ylab("Relative Autotrophic MAG abundance") +
  xlab("Depth") +
  theme_few() +
  theme(legend.position = "bottom", 
        strip.text = element_text(size = 16), 
        axis.title.y = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14)
        ) +
  scale_fill_manual(values = category_colors) + 
  scale_color_manual(values = category_colors) + 
  scale_x_discrete(limits=c("4000m","3000m","2000m", "1000m", "500m", "150m" ,"50m"))
  
plot

```

```{r}
ggsave(paste(rootdir, "refined_analysis/refined_figures/refined_figure2B.pdf", sep = ""), width = 15, height = 8, units = "in", dpi = 72)
```
